[workspace]
members = [
  "crates/spellwire-core",
  "crates/spellwire-native",
  "crates/spellwire-bench",
  "crates/spellwire-cli",
  "crates/spellwire-overlay",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/eunhhu/spellwire"
authors = ["Sunwoo Moon"]
rust-version = "1.81"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
